[8:45 AM] Pradeep Palagiri
name: CI/CD Pipeline
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Build and Test
        run: python hello_world.py
 
  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
 
    steps:
      - name: Deploy to Dev
        # Add deployment steps here
 
  deploy_qa:
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment:
      name: qa
 
    steps:
      - name: Deploy to QA
        # Add deployment steps here
 
  deploy_stage:
    runs-on: ubuntu-latest
    needs: deploy_qa
    environment:
      name: stage
 
    steps:
      - name: Deploy to Stage
        # Add deployment steps here
 
  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_stage
    environment:
      name: production
 
    steps:
      - name: Deploy to Production
        # Add deployment steps here
